BaiTap2/Source/GasStationProject/GasStationProject/Controllers/GasstationController.cs
using DataAccess.Repositories.IRepositories;
using DataAccess.UnitOfWork;
using GasStationProject.App_Core;
using GasStationProject.App_Core.LogWrapper;
using GasStationProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace GasStationProject.Controllers
{
    public class GasstationController : ControllerExtention
    {
        private IGasStationRepository _gasStationRepository;
        private IDistrictRepository _districtRepository;
        private IMTpyeRepository _mTpyeRepository;
        private IGasStationGasTypeRepository _gasStationGasTypeRepository;
        public GasstationController(
            IUnitOfWork unitOfWork, 
            ILogWrapper logWrapper, 
            IGasStationRepository gasStationRepository, 
            IDistrictRepository districtRepository,
            IMTpyeRepository mTpyeRepository,
            IGasStationGasTypeRepository gasStationGasTypeRepository
            ) : base(unitOfWork, logWrapper)
        {
            _gasStationRepository = gasStationRepository;
            _districtRepository = districtRepository;
            _mTpyeRepository = mTpyeRepository;
            _gasStationGasTypeRepository = gasStationGasTypeRepository;
        }
        // GET: Gasstation

        public ActionResult Add()
        {
            ViewBag.listDistrist = _districtRepository.GetAll().OrderBy(x => x.DistrictName);
            ViewBag.listGasType = _mTpyeRepository.GetAll().Where(x => x.TypeType == 3).ToList();
            ViewBag.ratingList = _mTpyeRepository.GetAll().Where(x=>x.TypeType ==4).ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Add(GasStationAddVM gasStationAddVM)
        {

            ViewBag.listDistrist = _districtRepository.GetAll().OrderBy(x => x.DistrictName);
            ViewBag.listGasType = _mTpyeRepository.GetAll().Where(x => x.TypeType == 3).ToList();
            ViewBag.ratingList = _mTpyeRepository.GetAll().Where(x => x.TypeType == 4).ToList();
            if (ModelState.IsValid)
            {
                if (_gasStationRepository.isNameExist(gasStationAddVM.GasStationName))
                {
                    ModelState.AddModelError("",Resources.Resource.E0003);
                    return View();
                }
                DataAccess.Models.GasStation gasStation = new DataAccess.Models.GasStation();
                try {
                    gasStation.GasStationName = gasStationAddVM.GasStationName;
                    gasStation.Address = gasStationAddVM.Address;
                    gasStation.OpeningTime = gasStationAddVM.OpeningTime;
                    gasStation.District = Convert.ToInt64(gasStationAddVM.District);
                    gasStation.Latitude = Convert.ToDouble(gasStationAddVM.Latitude);
                    gasStation.Longitude = Convert.ToDouble(gasStationAddVM.Longitude);
                    gasStation.Rating = gasStationAddVM.Rating;
                    gasStation.InsertedAt = DateTime.Now;
                    string userID = Session["個人ID"].ToString().Replace("{","").Replace("}","");
                    gasStation.InsertedBy = Convert.ToInt64(Regex.Replace(userID, @"\D", ""));
                    gasStation.UpdatedAt = DateTime.Now;
                    gasStation.UpdatedBy = gasStation.InsertedBy;                    
                    
                }
                catch {
                    ModelState.AddModelError("","Vui lòng kiểm tra lại.");
                    return View();
                }
                _gasStationRepository.Insert(gasStation);
                _unitOfWork.Commit();
                string[] listType = gasStationAddVM.Gatype.Split(Convert.ToChar(","));
                foreach (var item in listType)
                {
                    DataAccess.Models.GasStationGasType gasStationGasType = new DataAccess.Models.GasStationGasType();
                    gasStationGasType.GasStationId = gasStation.GasStationId;
                    gasStationGasType.GasType = item.Trim();
                    _gasStationGasTypeRepository.Insert(gasStationGasType);
                }
                _unitOfWork.Commit();
                return RedirectToAction("Index", "Home");   
            }
            ModelState.AddModelError("", "Có lỗi, vui lòng kiểm tra lại");
            return View();
        }

        public ActionResult Edit(int Id)
        {
            if( Id.ToString() == null )
            {
                return RedirectToAction("Error", "Error");
            }

            DataAccess.Models.GasStation gasStation = _gasStationRepository.FindById(Id);

            if (gasStation == null)
            {
                return RedirectToAction("NotFound", "Error");
            }

            ViewBag.listDistrist = _districtRepository.GetAll().OrderBy(x => x.DistrictName);
            ViewBag.listGasType = _mTpyeRepository.GetAll().Where(x => x.TypeType == 3).ToList();
            ViewBag.ratingList = _mTpyeRepository.GetAll().Where(x => x.TypeType == 4).ToList();
            GasStationAddVM gasStationAddVM = new GasStationAddVM();
            gasStationAddVM.GasStationName = gasStation.GasStationName;
            gasStationAddVM.Longitude = gasStation.Longitude.ToString();
            gasStationAddVM.Latitude = gasStation.Latitude.ToString();
            gasStationAddVM.District = gasStation.District.ToString();
            gasStationAddVM.Address = gasStation.Address;
            gasStationAddVM.OpeningTime = gasStation.OpeningTime;
            gasStationAddVM.Rating = gasStation.Rating;
            gasStationAddVM.GasStationId = gasStation.GasStationId;
            List<DataAccess.Models.GasStationGasType> listGasTypes = _gasStationGasTypeRepository.findByGasStationId(Id);
            foreach (var item in listGasTypes)
            {
                if(gasStationAddVM.Gatype == null)
                {
                    gasStationAddVM.Gatype += item.GasType;
                } else { gasStationAddVM.Gatype += "," + item.GasType; }
            }
            return View(gasStationAddVM);
        }

        [HttpPost]
        public ActionResult Edit(GasStationAddVM gasStationEdit)
        {
            ViewBag.listDistrist = _districtRepository.GetAll().OrderBy(x => x.DistrictName);
            ViewBag.listGasType = _mTpyeRepository.GetAll().Where(x => x.TypeType == 3).ToList();
            ViewBag.ratingList = _mTpyeRepository.GetAll().Where(x => x.TypeType == 4).ToList();
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Vui lòng kiểm tra lại dữ liệu");
                return View(gasStationEdit);
            }

            if (_gasStationRepository.isNameExist(gasStationEdit.GasStationName) && _gasStationRepository.FindById(gasStationEdit.GasStationId).GasStationName != gasStationEdit.GasStationName)
            {
                ModelState.AddModelError("", Resources.Resource.E0003);
                return View(gasStationEdit);
            }

            DataAccess.Models.GasStation gasStation = _gasStationRepository.FindById(gasStationEdit.GasStationId);
            try
            {
                gasStation.GasStationName = gasStationEdit.GasStationName;
                gasStation.Address = gasStationEdit.Address;
                gasStation.OpeningTime = gasStationEdit.OpeningTime;
                gasStation.District = Convert.ToInt64(gasStationEdit.District);
                gasStation.Latitude = Convert.ToDouble(gasStationEdit.Latitude);
                gasStation.Longitude = Convert.ToDouble(gasStationEdit.Longitude);
                gasStation.Rating = gasStationEdit.Rating;
                gasStation.InsertedAt = DateTime.Now;
                string userID = Session["個人ID"].ToString().Replace("{", "").Replace("}", "");
                gasStation.InsertedBy = Convert.ToInt64(Regex.Replace(userID, @"\D", ""));
                gasStation.UpdatedAt = DateTime.Now;
                gasStation.UpdatedBy = gasStation.InsertedBy;

            }
            catch
            {
                ModelState.AddModelError("", "Vui lòng kiểm tra lại.");
                return View();
            }
            _gasStationRepository.Update(gasStation);
            _unitOfWork.Commit();

            List<DataAccess.Models.GasStationGasType> gasTypeList = _gasStationGasTypeRepository.findByGasStationId(gasStationEdit.GasStationId);
            foreach (var item in gasTypeList)
            {
                _gasStationGasTypeRepository.Delete(item.GasStationGasTypeId);
            }
            _unitOfWork.Commit();
            string[] listType = gasStationEdit.Gatype.Split(Convert.ToChar(","));
            foreach (var item in listType)
            {
                DataAccess.Models.GasStationGasType gasStationGasType = new DataAccess.Models.GasStationGasType();
                gasStationGasType.GasStationId = gasStation.GasStationId;
                gasStationGasType.GasType = item.Trim();
                _gasStationGasTypeRepository.Insert(gasStationGasType);
            }
            _unitOfWork.Commit();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Delete( long Id)
        {
            if (Id.ToString() == null)
            {
                return RedirectToAction("Error", "Error");
            }

            DataAccess.Models.GasStation gasStation = _gasStationRepository.FindById(Id);

            if (gasStation == null)
            {
                return RedirectToAction("NotFound", "Error");
            }

            ViewBag.listDistrist = _districtRepository.GetAll().OrderBy(x => x.DistrictName);
            ViewBag.listGasType = _mTpyeRepository.GetAll().Where(x => x.TypeType == 3).ToList();
            ViewBag.ratingList = _mTpyeRepository.GetAll().Where(x => x.TypeType == 4).ToList();

BaiTap2/Source/GasStationProject/GasStationProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GasStationProject.App_Core;
using System.IO;
using CsvHelper;
using CsvHelper.Configuration;
using System.Text;
using DataAccess.Repositories.IRepositories;
using DataAccess.UnitOfWork;
using GasStationProject.App_Core.LogWrapper;
using GasStationProject.Models;
using System.Web.Script.Serialization;

namespace GasStationProject.Controllers
{
    
    public class HomeController : ControllerExtention
    {
        private IGasStationRepository _gasStationRepository;
        private IGasStationGasTypeRepository _gasStationGasTypeRepository;
        private IDistrictRepository _districtRepository;
        private IMTpyeRepository _mTypeRepository;
        static public int countPage;
        public HomeController(IUnitOfWork unitOfWork, ILogWrapper logWrapper, 
            IGasStationRepository gasStationRepository,
            IGasStationGasTypeRepository gasStationGasTypeRepository,
            IDistrictRepository districtRepository,
            IMTpyeRepository mTypeRepository
            ) : base(unitOfWork, logWrapper)
        {
            _gasStationRepository = gasStationRepository;
            _gasStationGasTypeRepository = gasStationGasTypeRepository;
            _districtRepository = districtRepository;
            _mTypeRepository = mTypeRepository;
        }


        public ActionResult Index()
        {
            ViewBag.listDistrist = _districtRepository.GetAll().OrderBy(x=>x.DistrictName);
            ViewBag.listGasType = _mTypeRepository.GetAll().Where(x => x.TypeType == 3).ToList();
            ViewBag.pageCount = _gasStationRepository.GetAll().Count();
            return View();
        }

        public ActionResult MapList()
        {
            ViewBag.listDistrist = _districtRepository.GetAll().OrderBy(x => x.DistrictName);
            ViewBag.listGasType = _mTypeRepository.GetAll().Where(x => x.TypeType == 3).ToList();
            ViewBag.pageCount = _gasStationRepository.GetAll().Count();
            return View();
        }

        [ValidateAntiForgeryToken]
        public JsonResult gastationFillter(string data)
        {
            JavaScriptSerializer json_serializer = new JavaScriptSerializer();
            dynamic queryData = json_serializer.DeserializeObject(data);
            string queryGasName = queryData["gasName"];
            string querygasTpye = queryData["gasType"] ;
            string queryDistrict = queryData["districtID"];
            int queryPage = Convert.ToInt32(queryData["selectPage"]);
            
            // Dung để kiểm tra xem có tồn tại gastype hay không.
            bool checkType(string qr, List<DataAccess.Models.GasStationGasType> gt)
                {
                    foreach (var item in gt)
                    {
                        if(qr.Contains(item.GasType)) { return true; }
                    }
                    return false;
                }

            //Fillter theo các điều kiện truyền vào
            var gasStationsN = _gasStationRepository.GetAll().Where(x=>
                (queryGasName != null ?  x.GasStationName.ToLowerInvariant().Contains(queryGasName) :true) &&
                ( querygasTpye != null ? checkType(querygasTpye, x.GasStationGasType.ToList()): true ) &&
                (queryDistrict != null ? x.District == (long)Convert.ToDouble(queryDistrict): true) 
            );

            countPage = gasStationsN.Count();

            var gasStations = gasStationsN.Skip((queryPage - 1) * 10).Take(10).ToList();

            List<GasStationVM> result = new List<GasStationVM>();

            //Add gasstartion vào bên trong result
            foreach (var item in gasStations)
            {
                GasStationVM gasStationVM = new GasStationVM();
                gasStationVM.GasStationName = item.GasStationName;
                int count = 0;
                foreach (var type in item.GasStationGasType)
                {
                    if (count == 0)
                    {
                        gasStationVM.GasType += _mTypeRepository.getTypeText(type.GasType, 3);
                        count++;
                    }
                    gasStationVM.GasType += ", " + _mTypeRepository.getTypeText(type.GasType, 3);
                }
                gasStationVM.GasStationId = item.GasStationId;
                gasStationVM.DistrictName = _districtRepository.FindById(item.District).DistrictName;
                gasStationVM.Longitude = item.Longitude;
                gasStationVM.Latitude = item.Latitude;
                gasStationVM.Rating = _mTypeRepository.getTypeText(item.Rating, 4);
                result.Add(gasStationVM);
            }

            return Json(result);
        }

        public JsonResult getCountPage()
        {
            return Json(new { page = countPage});
        }

    }
}

BaiTap2/Source/GasStationProject/GasStationProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
    var listDistrist = ViewBag.listDistrist;
    var listGatype = ViewBag.listGasType;
    var countPage = ViewBag.pageCount;
}

@using System.Web.Optimization

@Html.AntiForgeryToken()

<h2 class="text-center mb-5">ガソリンスタンド一覧</h2>

<div class="group-data">
    @* Begin filter *@
    <div class="card mb-0 pb-0">
        <div class="card-header">
            Filter
        </div>
        <div class="card-body">
            <div class="px-lg-5">
                <div class="form-group d-flex">
                    <label for="input-name-gas" class="w-25">ガソリンスタンド名: </label>
                    <input type="text" class="form-control w-100" id="input-name-gas" placeholder="Enter name gas station ...">
                </div>
                <div class="form-group d-flex">
                    <label class="w-25">種類:  </label>
                    <div class="w-100">
                        <div class="form-check ">
                            <input class="form-check-input" type="radio" name="selectTypeGas" id="selectAll" value="" checked>
                            <label class="form-check-label" for="selectAll">
                                All
                            </label>
                        </div>
                        @foreach (var item in listGatype)
                        {
                            <div class="form-check ">
                                <input class="form-check-input" type="radio" name="selectTypeGas" id=@item.TypeText value=@item.TypeCode>
                                <label class="form-check-label" for="@item.TypeText">
                                    @item.TypeText
                                </label>
                            </div>
                        }
                    </div>
                </div>

                <div class="form-group d-flex">
                    <label class="w-25" for="selectDistrict">地区: </label>
                    <select class="form-control w-100" id="selectDistrict">
                        <option value="">Không chọn</option>
                        @foreach (var item in listDistrist)
                        {
                            <option value="@item.DistrictId">@item.DistrictName</option>
                        }

                    </select>
                </div>

            </div>
            <div class="w-100 text-center">
                <button class="btn btn-primary w-25" id="search-with-query">検索</button>
            </div>
        </div>

        <div class="w-100 text-left">
            <button class="btn btn-primary ml-3 mb-3 col-md-2">@Html.ActionLink("登録", "Add", "Gasstation",null, new { @class="text-white w-100 d-block"})</button>
        </div>

    </div>
    @* End filter *@
    @* Begin table *@
<div class="container_table_gas">
    @*Begin Form show gas station*@
    <table class="table table-hover bg-white table-bordered">
        <thead class="bg-light text-center">
            <tr>
                <th scope="col">ガソリンスタンド名</th>
                <th scope="col">種類</th>
                <th scope="col">地区</th>
                <th scope="col">　Longitude, Latitude</th>
                <th scope="col">　評価</th>
                <th scope="col">Option</th>
            </tr>
        </thead>
        <tbody class="body-table">
            @* javascript will process *@
        </tbody>
    </table>

    <div class="mb-5 mt-0 d-flex pagination-box justify-content-center w-100">
        <nav aria-label="...">
            <ul class="pagination">
                <li class="page-item disabled  controll controllerFirst">
                    <span class="page-link">First</span>
                </li>
                <li class="page-item disabled  controll controllerPre">
                    <span class="page-link">Previous</span>
                </li>
                <li class="page-item active"><span class="page-link">1</span></li>
                @if (countPage > 1)
                {
                    for (int i = 2; i <= Math.Ceiling((double)countPage/10); i++)
                    {
                        <li class="page-item"><span class="page-link">@(i )</span></li>
                    }
                }
                @if (countPage <= 10)
                {
                    <li class="page-item disabled controll controllerNext">
                        <span class="page-link">Next</span>
                    </li>
                    <li class="page-item disabled  controll controllerLast">
                        <span class="page-link">Last</span>
                    </li>
                }
                else
                {
                    <li class="page-item controll controllerNext">
                        <span class="page-link">Next</span>
                    </li>
                    <li class="page-item  controll controllerLast">
                        <span class="page-link">Last</span>
                    </li>
                }
            </ul>
        </nav>
    </div>

    @*End Form show gas station*@


</div>

</div>


@section PageScript {
    @Scripts.Render("~/content/HomeControler")
}

@section PageStyle {
    @Styles.Render("~/content/HomeCSS")
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBSxLoeVH330_x1JYvbWXnNmGFAKFKOPeE" async defer></script>
}

BaiTap2/Source/GasStationProject/GasStationProject/Views/Home/MapList.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
    var listDistrist = ViewBag.listDistrist;
    var listGatype = ViewBag.listGasType;
    var countPage = ViewBag.pageCount;
}

@using System.Web.Optimization

@Html.AntiForgeryToken()

<h2 class="text-center mb-5">ガソリンスタンド一覧</h2>

<div class="group-data">
    @* Begin filter *@
    <div class="card mb-0 pb-0">
        <div class="card-header">
            Filter
        </div>
        <div class="w-100 text-right">
            <button class="btn btn-primary ml-3 mb-3 col-md-2">@Html.ActionLink("View List", "Index", "Home", null, new { @class = "text-white w-100 d-block" })</button>
        </div>
        <div class="card-body">
            <div class="px-lg-5">
                <div class="form-group d-flex">
                    <label for="input-name-gas" class="w-25">ガソリンスタンド名: </label>
                    <input type="text" class="form-control w-100" id="input-name-gas" placeholder="Enter name gas station ...">
                </div>
                <div class="form-group d-flex group-gastype">
                    <label class="w-25">種類:  </label>
                    <div class="w-100">
                        <div class="form-check ">
                        </div>
                        @foreach (var item in listGatype)
                        {
                            <div class="form-check ">
                                <input class="form-check-input" type="checkbox" name="selectTypeGas" id=@item.TypeText value=@item.TypeCode>
                                <label class="form-check-label" for="@item.TypeText">
                                    @item.TypeText
                                </label>
                            </div>
                        }
                    </div>
                </div>

                <div class="form-group d-flex">
                    <label class="w-25" for="selectDistrict">地区: </label>
                    <select class="form-control w-100" id="selectDistrict">
                        <option value="">Không chọn</option>
                        @foreach (var item in listDistrist)
                        {
                            <option value="@item.DistrictId">@item.DistrictName</option>
                        }

                    </select>
                </div>

            </div>
            <div class="w-100 text-center">
                <button class="btn btn-primary w-25" id="search-with-query">検索</button>
            </div>
        </div>

        <div class="w-100 text-left">
            <button class="btn btn-primary ml-3 mb-3 col-md-2">@Html.ActionLink("登録", "Add", "Gasstation", null, new { @class = "text-white w-100 d-block" })</button>
        </div>

    </div>
    @* End filter *@

    @* Begin table *@
    <div class="container_map_gas">
        
        <div id="map-result"></div>
        
    </div>


    @* Begin pagination *@
    <div class="pb-5 mt-5 d-flex pagination-box justify-content-center w-100">
        <nav aria-label="...">
            <ul class="pagination">
                <li class="page-item disabled  controll controllerFirst">
                    <span class="page-link">First</span>
                </li>
                <li class="page-item disabled  controll controllerPre">
                    <span class="page-link">Previous</span>
                </li>
                <li class="page-item active"><span class="page-link">1</span></li>
                @if (countPage > 1)
                {
                    for (int i = 2; i <= Math.Ceiling((double)countPage / 10); i++)
                    {
                        <li class="page-item"><span class="page-link">@(i)</span></li>
                    }
                }
                @if (countPage <= 10)
                {
                    <li class="page-item disabled controll controllerNext">
                        <span class="page-link">Next</span>
                    </li>
                    <li class="page-item disabled  controll controllerLast">
                        <span class="page-link">Last</span>
                    </li>
                }
                else
                {
                    <li class="page-item controll controllerNext">
                        <span class="page-link">Next</span>
                    </li>
                    <li class="page-item  controll controllerLast">
                        <span class="page-link">Last</span>
                    </li>
                }
            </ul>
        </nav>
    </div>

</div>


@section PageScript {
    @Scripts.Render("~/content/MapList")
}

@section PageStyle {
    @Styles.Render("~/content/HomeCSS")
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBSxLoeVH330_x1JYvbWXnNmGFAKFKOPeE" async defer></script>
}